import assert from "node:assert/strict";
import { existsSync, mkdirSync, mkdtempSync, readFileSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import test from "node:test";
import { initializeProjectContext } from "./project-context.js";
import { settingsForWorkspace } from "./settings.js";

test("generates useful project context from repository files", () => {
  const workspace = mkdtempSync(join(tmpdir(), "fleet-context-"));
  const repository = join(workspace, "repository");
  const settings = settingsForWorkspace(join(workspace, "fleet"));
  mkdirSync(repository, { recursive: true });
  writeFileSync(join(repository, "README.md"), "# Billing API\n\nProcesses invoices for the billing team.\n", "utf8");
  writeFileSync(join(repository, "package.json"), JSON.stringify({ name: "billing-api", scripts: { test: "node --test", build: "tsc" } }), "utf8");

  const context = initializeProjectContext(settings, "Billing API", repository);
  const project = readFileSync(context.project, "utf8");
  const status = readFileSync(context.status, "utf8");

  assert.equal(context.directory, repository);
  assert.equal(context.project, join(repository, "PROJECT.md"));
  assert.equal(existsSync(context.directory), true);
  assert.match(project, /Processes invoices/);
  assert.match(project, /npm run test: node --test/);
  assert.match(project, /Inferred from the repository README/);
  assert.match(status, /Generated by Fleet/);
  assert.match(status, /Working tree: clean/);
});
