import { execFileSync } from "node:child_process";
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import type { FleetSnapshot, Project } from "./domain.js";
import type { FleetSettings } from "./settings.js";

export interface ProjectContextPaths {
  directory: string;
  project: string;
  status: string;
  decisions: string;
}

export function getProjectContextPaths(_settings: FleetSettings, _name: string, repositoryPath: string): ProjectContextPaths {
  const directory = repositoryPath;
  return {
    directory,
    project: join(directory, "PROJECT.md"),
    status: join(directory, "STATUS.md"),
    decisions: join(directory, "DECISIONS.md"),
  };
}

export function initializeProjectContext(settings: FleetSettings, name: string, repositoryPath: string): ProjectContextPaths {
  const paths = getProjectContextPaths(settings, name, repositoryPath);
  mkdirSync(paths.directory, { recursive: true });
  if (!existsSync(paths.project) || isBootstrapPlaceholder(paths.project)) {
    writeFileSync(paths.project, buildProjectContext(name, repositoryPath), "utf8");
  }
  if (!existsSync(paths.decisions)) {
    writeFileSync(paths.decisions, `# ${name} decisions\n\nFleet records durable technical decisions here. Keep entries short and include context, decision, and consequences.\n`, "utf8");
  }
  if (!existsSync(paths.status)) refreshProjectStatus(settings, name, repositoryPath, "Project context initialized from repository inspection.");
  return paths;
}

export function refreshProjectStatus(settings: FleetSettings, name: string, repositoryPath: string, activity: string): ProjectContextPaths {
  const paths = getProjectContextPaths(settings, name, repositoryPath);
  mkdirSync(paths.directory, { recursive: true });
  const branch = runGit(repositoryPath, ["branch", "--show-current"]) || "unknown";
  const remote = runGit(repositoryPath, ["remote", "get-url", "origin"]) || "not configured";
  const latestCommit = runGit(repositoryPath, ["log", "-1", "--pretty=format:%h %s"]) || "no commits found";
  const workingTree = runGit(repositoryPath, ["status", "--short"]) ? "has local changes" : "clean";
  writeFileSync(paths.status, [
    `# ${name} - Fleet status`,
    "",
    "> Generated by Fleet. SQLite remains the source of truth for live agents and tasks.",
    "",
    `- Updated: ${new Date().toISOString()}`,
    `- Repository: ${repositoryPath}`,
    `- Branch: ${branch}`,
    `- Remote: ${remote}`,
    `- Working tree: ${workingTree}`,
    `- Latest commit: ${latestCommit}`,
    "",
    "## Latest activity",
    "",
    activity,
    "",
    "## Next steps",
    "",
    "- Review active Fleet tasks and open pull requests from the captain.",
    "- Update PROJECT.md only when stable project knowledge changes.",
  ].join("\n") + "\n", "utf8");
  return paths;
}

export function refreshProjectStatusFromFleet(
  settings: FleetSettings,
  project: Project,
  snapshot: FleetSnapshot,
  activity: string,
): ProjectContextPaths {
  const paths = getProjectContextPaths(settings, project.name, project.rootPath);
  mkdirSync(paths.directory, { recursive: true });
  const tasks = snapshot.tasks.filter((task) => task.projectId === project.id);
  const taskIds = new Set(tasks.map((task) => task.id));
  const agents = snapshot.agents.filter((agent) => taskIds.has(agent.taskId));
  const pendingMessageIds = new Set(snapshot.decisions.filter((decision) => decision.status === "pending").map((decision) => decision.messageId));
  const pendingDecisions = snapshot.messages.filter((message) => message.taskId && taskIds.has(message.taskId) && pendingMessageIds.has(message.id));
  const activeTasks = tasks.filter((task) => ["pending", "ready", "running", "review"].includes(task.status));
  const recentTasks = [...tasks].sort((left, right) => right.updatedAt.localeCompare(left.updatedAt)).slice(0, 6);
  const recentActivity = (snapshot.recentActivity ?? []).filter((entry) => entry.projectName === project.name).slice(0, 8);
  const branch = runGit(project.rootPath, ["branch", "--show-current"]) || "unknown";
  const remote = runGit(project.rootPath, ["remote", "get-url", "origin"]) || "not configured";
  const latestCommit = runGit(project.rootPath, ["log", "-1", "--pretty=format:%h %s"]) || "no commits found";
  const activeLines = activeTasks.length === 0
    ? ["- None."]
    : activeTasks.map((task) => {
      const taskAgents = agents.filter((agent) => agent.taskId === task.id && !["completed", "failed", "cancelled"].includes(agent.status));
      const owners = taskAgents.length ? taskAgents.map((agent) => `${agent.role}:${agent.status}`).join(", ") : "no active agent";
      return `- ${task.status} | ${task.spec.kind}/${task.spec.deliveryMode} | ${task.title} | ${owners}`;
    });
  const taskLines = recentTasks.length === 0
    ? ["- None."]
    : recentTasks.map((task) => `- ${task.status} | ${task.title} | updated ${task.updatedAt}`);
  const decisionLines = pendingDecisions.length === 0
    ? ["- None."]
    : pendingDecisions.map((message) => `- ${message.priority.toUpperCase()} | ${message.text}`);
  const activityLines = recentActivity.length === 0
    ? ["- No recorded activity."]
    : recentActivity.map((entry) => `- ${entry.createdAt} | ${entry.eventType} ${entry.entityType}`);
  writeFileSync(paths.status, [
    `# ${project.name} - Fleet status`,
    "",
    "> Generated from Fleet events. SQLite is the source of truth; this file is concise project memory.",
    "",
    `- Updated: ${new Date().toISOString()}`,
    `- Repository: ${project.rootPath}`,
    `- Branch: ${branch}`,
    `- Remote: ${remote}`,
    `- Latest commit: ${latestCommit}`,
    `- Tasks: ${tasks.length} total, ${activeTasks.length} active`,
    `- Agents: ${agents.filter((agent) => !["completed", "failed", "cancelled"].includes(agent.status)).length} active`,
    "",
    "## Latest outcome",
    "",
    activity,
    "",
    "## Active work",
    "",
    ...activeLines,
    "",
    "## Pending decisions",
    "",
    ...decisionLines,
    "",
    "## Recent tasks",
    "",
    ...taskLines,
    "",
    "## Recent Fleet events",
    "",
    ...activityLines,
  ].join("\n") + "\n", "utf8");
  return paths;
}

function buildProjectContext(name: string, repositoryPath: string): string {
  const packageInfo = readPackageInfo(repositoryPath);
  const overview = readOverview(repositoryPath);
  const remote = runGit(repositoryPath, ["remote", "get-url", "origin"]) || "not configured";
  const branch = runGit(repositoryPath, ["branch", "--show-current"]) || "unknown";
  const latestCommit = runGit(repositoryPath, ["log", "-1", "--pretty=format:%h %s"]) || "no commits found";
  const purpose = inferPurpose(overview);
  return [
    `# ${name}`,
    "",
    "> Durable project context maintained by Fleet. Keep this file concise and update it only when stable knowledge changes.",
    "",
    "## Purpose",
    "",
    purpose ? `> Inferred from the repository README. Confirm or refine this summary.\n\n${purpose}` : "[NEEDS HUMAN INPUT] Describe the product or outcome this project exists to deliver.",
    "",
    "## Repository",
    "",
    `- Root: ${repositoryPath}`,
    `- Remote: ${remote}`,
    `- Current branch at initialization: ${branch}`,
    `- Latest commit at initialization: ${latestCommit}`,
    "",
    "## Overview from repository",
    "",
    overview || "[NEEDS HUMAN INPUT] Add a short repository overview.",
    "",
    "## Technology and commands",
    "",
    packageInfo || "[NEEDS HUMAN INPUT] Add the main technologies and validation commands.",
    "",
    "## Working agreements",
    "",
    "- Read the repository AGENTS.md or equivalent instructions before modifying files.",
    "- Work on an isolated branch and run the required validation before opening a pull request.",
    "- Record durable technical choices in DECISIONS.md through Fleet.",
    "",
    "## Context maintenance",
    "",
    "- STATUS.md is generated and describes the latest operational state.",
    "- Keep this file stable, factual, and short enough to read at the start of a task.",
  ].join("\n") + "\n";
}

function isBootstrapPlaceholder(path: string): boolean {
  try {
    return /^# .+\r?\n\r?\nFleet project metadata\.\r?\n?$/.test(readFileSync(path, "utf8"));
  } catch {
    return false;
  }
}

function readPackageInfo(repositoryPath: string): string {
  const packagePath = join(repositoryPath, "package.json");
  if (!existsSync(packagePath)) return "";
  try {
    const packageJson = JSON.parse(readFileSync(packagePath, "utf8")) as { name?: string; version?: string; scripts?: Record<string, string> };
    const lines = [`- Package: ${packageJson.name ?? "unknown"}${packageJson.version ? ` (${packageJson.version})` : ""}`];
    for (const [name, command] of Object.entries(packageJson.scripts ?? {}).slice(0, 12)) lines.push(`- npm run ${name}: ${command}`);
    return lines.join("\n");
  } catch {
    return "[Repository has a package.json that Fleet could not parse.]";
  }
}

function readOverview(repositoryPath: string): string {
  const readmePath = ["README.md", "readme.md", "README"]
    .map((name) => join(repositoryPath, name))
    .find((path) => existsSync(path));
  if (!readmePath) return "";
  try {
    const lines = readFileSync(readmePath, "utf8").split(/\r?\n/).filter((line) => line.trim()).slice(0, 18);
    const text = lines.join("\n").trim();
    return text.length > 1600 ? `${text.slice(0, 1600)}\n[...]` : text;
  } catch {
    return "";
  }
}

function inferPurpose(overview: string): string {
  return overview
    .split(/\r?\n/)
    .filter((line) => line.trim() && !line.trim().startsWith("#"))
    .slice(0, 2)
    .join("\n")
    .trim();
}

function runGit(repositoryPath: string, args: string[]): string {
  try {
    return execFileSync("git", ["-C", repositoryPath, ...args], { encoding: "utf8", stdio: "pipe" }).trim();
  } catch {
    return "";
  }
}
