import assert from "node:assert/strict";
import { existsSync, mkdirSync, mkdtempSync, readFileSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import test from "node:test";
import { initializeProjectContext, refreshProjectStatusFromFleet } from "./project-context.js";
import { settingsForWorkspace } from "./settings.js";
import { messageFixture, snapshotFixture, taskFixture } from "./test-fixtures.js";

test("generates useful project context from repository files", () => {
  const workspace = mkdtempSync(join(tmpdir(), "fleet-context-"));
  const repository = join(workspace, "repository");
  const settings = settingsForWorkspace(join(workspace, "fleet"));
  mkdirSync(repository, { recursive: true });
  writeFileSync(join(repository, "README.md"), "# Billing API\n\nProcesses invoices for the billing team.\n", "utf8");
  writeFileSync(join(repository, "package.json"), JSON.stringify({ name: "billing-api", scripts: { test: "node --test", build: "tsc" } }), "utf8");

  const context = initializeProjectContext(settings, "Billing API", repository);
  const project = readFileSync(context.project, "utf8");
  const status = readFileSync(context.status, "utf8");

  assert.equal(context.directory, repository);
  assert.equal(context.project, join(repository, "PROJECT.md"));
  assert.equal(existsSync(context.directory), true);
  assert.match(project, /Processes invoices/);
  assert.match(project, /npm run test: node --test/);
  assert.match(project, /Inferred from the repository README/);
  assert.match(status, /Generated by Fleet/);
  assert.match(status, /Working tree: clean/);
});

test("generates STATUS from Fleet tasks and canonical pending decisions", () => {
  const workspace = mkdtempSync(join(tmpdir(), "fleet-context-state-"));
  const repository = join(workspace, "repository");
  mkdirSync(repository, { recursive: true });
  const project = { id: "project-1", name: "Fleet", rootPath: repository, createdAt: "2026-08-26T10:00:00.000Z" };
  const task = taskFixture({ projectId: project.id, title: "Supervise workers", status: "running" });
  const message = messageFixture({ taskId: task.id, type: "approval", text: "Choose cleanup policy", requiresHuman: true, decisionId: "decision-1" });
  const settings = settingsForWorkspace(join(workspace, "fleet"));
  const paths = refreshProjectStatusFromFleet(settings, project, snapshotFixture({
    projects: [project], tasks: [task], messages: [message], decisions: [{
      id: "decision-1", messageId: message.id, taskId: task.id, agentId: message.agentId, status: "pending",
      question: message.text, resolution: null, decidedBy: null, createdAt: message.createdAt, resolvedAt: null,
    }],
  }), "Supervisor synchronized the project.");
  const status = readFileSync(paths.status, "utf8");
  assert.match(status, /Supervise workers/);
  assert.match(status, /Choose cleanup policy/);
  assert.match(status, /Supervisor synchronized/);
});
